services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: postgresql://mercado_jghe_user:NuB8IqLQg4PyThnG8jPQhNMlfVw6KE2T@dpg-d1sis215pdvs7397dr10-a.oregon-postgres.render.com:5432/mercado_jghe?sslmode=require
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]

  tests:
    build:
      context: ./backend
    volumes:   
      - ./backend:/app
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://mercado_jghe_user:NuB8IqLQg4PyThnG8jPQhNMlfVw6KE2T@dpg-d1sis215pdvs7397dr10-a.oregon-postgres.render.com:5432/mercado_jghe?sslmode=require
    command: ["pytest", "--disable-warnings", "-v"]
    depends_on:
      - backend
      
  lint:
    build: 
      context: ./backend
    volumes:
      - ./backend:/app
    environment:
      - PYTHONPATH=/app
    command: ["pylint", "--disable=R,C", "."]
