version: "3.8"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: mercado
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  tests:
    build:
      context: ./backend
    command: >
      sh -c "pytest app/tests --disable-warnings"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "mysql+aiomysql://user:user123@db:3306/mercado"